# Generated by Django 4.1 on 2023-11-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mosquitosystem",
            name="secret_key",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mosquitoimages",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="mosquitosystem",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
