# Generated by Django 5.0.3 on 2024-03-30 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_image_images_photo_alter_system_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='coverage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='core.areacoverage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.areacoverage'),
        ),
    ]
