# Generated by Django 5.0.3 on 2024-03-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_system_coverage_alter_images_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatus',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='systemwaterlevel',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
