# Generated by Django 5.0.3 on 2024-04-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_systemstatus_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="score",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="images",
            name="x1",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="images",
            name="x2",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="images",
            name="y1",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="images",
            name="y2",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
