# Generated by Django 5.0.3 on 2024-04-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_images_score_images_x1_images_x2_images_y1_images_y2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="images",
            name="score",
        ),
        migrations.RemoveField(
            model_name="images",
            name="x1",
        ),
        migrations.RemoveField(
            model_name="images",
            name="x2",
        ),
        migrations.RemoveField(
            model_name="images",
            name="y1",
        ),
        migrations.RemoveField(
            model_name="images",
            name="y2",
        ),
        migrations.CreateModel(
            name="Detections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detection_id", models.IntegerField()),
                ("x1", models.FloatField()),
                ("y1", models.FloatField()),
                ("x2", models.FloatField()),
                ("y2", models.FloatField()),
                ("score", models.FloatField()),
                ("detected_time", models.DateTimeField()),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="core.system",
                    ),
                ),
            ],
            options={
                "unique_together": {("detection_id", "system")},
            },
        ),
    ]
